# Default initial positions for piper

joint_state_publisher:
  ros__parameters:
    zeros:
      joint1: 0.0
      joint2: 0.0
      joint3: 0.0
      joint4: 0.0
      joint5: 0.0
      joint6: 0.0
      joint7: 0.0